
on:
  push:
    #branches: [ main ]
  pull_request:
    #branches: [ main ]

jobs:
  linux-win:
    runs-on: ubuntu-latest
    container:
      image: electronuserland/builder:wine
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: build
        env:
          CI: false
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          id
          yarn app-linux
          echo "finished linux"
          chown -R root:root /github/home
          yarn app-windows
          echo "finished windows"
          ls -la dist
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: build
        env:
          CI: false
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          API_KEY_ID: ${{ secrets.API_KEY_ID }}
          API_KEY_ISSUER_ID: ${{ secrets.API_KEY_ISSUER_ID }}
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.API_KEY_ID }}.p8
          yarn app-macos
          ls -la dist
